"""RoboTHOR dataset adapter.

Reads episodes generated by scripts/generate_robothor_data.py, which
are saved as::

    data/robothor/
        episode_00000/
            rgb/frame_000000.png, ...
            depth/frame_000000.npy, ...
            metadata.npz
        episode_00001/
            ...
        episodes_metadata.json
"""

from __future__ import annotations

import glob
import json
import os
from typing import Any, Dict, List

import numpy as np
import cv2

from data_adapters.base_adapter import BaseDatasetAdapter


class RoboTHORAdapter(BaseDatasetAdapter):
    """Adapter for RoboTHOR generated episodes.

    Parameters
    ----------
    data_dir : str
        Path to the robothor episode directory.
    scan_dim : int
        Number of Scan64 beams.
    image_size : tuple[int, int]
        Target (H, W) for RGB images.
    load_scan64_from_meta : bool
        If True, load pre-computed Scan64 from metadata.npz instead
        of recomputing from depth (faster).
    """

    def __init__(
        self,
        data_dir: str,
        scan_dim: int = 64,
        image_size: tuple[int, int] = (224, 224),
        load_scan64_from_meta: bool = True,
    ) -> None:
        super().__init__(data_dir, scan_dim, image_size)
        self.load_scan64_from_meta = load_scan64_from_meta

    # ------------------------------------------------------------------
    # Loading
    # ------------------------------------------------------------------

    def load_episodes(self) -> List[Dict[str, Any]]:
        """Load all episode directories."""
        episode_dirs = sorted(glob.glob(
            os.path.join(self.data_dir, "episode_*")
        ))

        if not episode_dirs:
            raise FileNotFoundError(
                f"No episode_* directories found in {self.data_dir}. "
                f"Run scripts/generate_robothor_data.py first."
            )

        episodes = []
        for ep_dir in episode_dirs:
            ep = self._load_single_episode(ep_dir)
            if ep is not None:
                episodes.append(ep)

        print(f"[RoboTHORAdapter] Loaded {len(episodes)} episodes from {self.data_dir}")
        return episodes

    def _load_single_episode(self, ep_dir: str) -> Dict[str, Any] | None:
        """Load a single episode from directory."""
        meta_path = os.path.join(ep_dir, "metadata.npz")
        if not os.path.exists(meta_path):
            print(f"  WARNING: no metadata.npz in {ep_dir}, skipping")
            return None

        meta = dict(np.load(meta_path, allow_pickle=True))

        # RGB frames
        rgb_dir = os.path.join(ep_dir, "rgb")
        rgb_paths = sorted(glob.glob(os.path.join(rgb_dir, "frame_*.png")))

        if not rgb_paths:
            print(f"  WARNING: no RGB frames in {rgb_dir}, skipping")
            return None

        # Depth frames
        depth_dir = os.path.join(ep_dir, "depth")
        depth_paths = sorted(glob.glob(os.path.join(depth_dir, "frame_*.npy")))

        return {
            "ep_dir": ep_dir,
            "rgb_paths": rgb_paths,
            "depth_paths": depth_paths,
            "meta": meta,
        }

    # ------------------------------------------------------------------
    # Conversion
    # ------------------------------------------------------------------

    def convert_episode(self, raw_episode: Dict[str, Any]) -> Dict[str, Any]:
        """Convert a RoboTHOR episode to unified format.

        RoboTHOR episodes from the generator already have most fields
        pre-computed in metadata.npz, so this is mostly a data
        reorganization step.
        """
        rgb_paths = raw_episode["rgb_paths"]
        depth_paths = raw_episode["depth_paths"]
        meta = raw_episode["meta"]
        T = len(rgb_paths)

        # Most data is already in metadata.npz
        actions = meta.get("actions", np.zeros((T, 3), dtype=np.float32))
        rewards = meta.get("rewards", np.zeros(T, dtype=np.float32))
        dones = meta.get("dones", np.zeros(T, dtype=bool))
        goals = meta.get("goal", np.zeros((T, 3), dtype=np.float32))
        states = meta.get("state", np.zeros((T, 3), dtype=np.float32))
        prev_actions = meta.get("prev_action", np.zeros((T, 3), dtype=np.float32))
        collisions = meta.get("collision", np.zeros(T, dtype=bool))
        interventions = meta.get("intervention", np.zeros(T, dtype=bool))
        goal_reached = meta.get("goal_reached", np.zeros(T, dtype=bool))
        robot_positions = meta.get(
            "robot_position", np.zeros((T, 2), dtype=np.float32)
        )
        goal_positions = meta.get(
            "goal_position", np.zeros((T, 2), dtype=np.float32)
        )

        # If scan64 is pre-computed in metadata, use it directly
        if self.load_scan64_from_meta and "scan64" in meta:
            scan64 = meta["scan64"]
        else:
            scan64 = np.full((T, self.scan_dim), np.nan, dtype=np.float32)

        # Load RGB and depth frames
        rgb_frames = np.zeros((T, *self.image_size, 3), dtype=np.uint8)
        depth_frames = np.zeros((T, *self.image_size), dtype=np.float32)

        for t in range(T):
            # RGB
            rgb = cv2.imread(rgb_paths[t])
            if rgb is not None:
                rgb = cv2.cvtColor(rgb, cv2.COLOR_BGR2RGB)
                if rgb.shape[:2] != self.image_size:
                    rgb = self._resize_rgb(rgb, self.image_size)
                rgb_frames[t] = rgb

            # Depth
            if t < len(depth_paths) and os.path.exists(depth_paths[t]):
                depth = np.load(depth_paths[t])
                if depth.shape[:2] != self.image_size:
                    depth = cv2.resize(
                        depth,
                        (self.image_size[1], self.image_size[0]),
                        interpolation=cv2.INTER_NEAREST,
                    )
                depth_frames[t] = depth

                # Compute Scan64 from depth if not in metadata
                if not self.load_scan64_from_meta or "scan64" not in meta:
                    scan64[t] = self.compute_scan64_from_depth(
                        depth, self.scan_dim
                    )

        return {
            "observations": {
                "rgb": rgb_frames,
                "depth": depth_frames,
                "scan64": scan64,
                "state": states,
                "goal": goals,
                "prev_action": prev_actions,
            },
            "actions": actions,
            "rewards": rewards,
            "dones": dones,
            "info": {
                "collision": collisions,
                "intervention": interventions,
                "goal_reached": goal_reached,
                "robot_position": robot_positions,
                "goal_position": goal_positions,
            },
        }
