#!/usr/bin/env python
"""Convert public dataset → unified format → LeRobot dataset.

Supported datasets:
    robothor  — RoboTHOR episodes generated by scripts/generate_robothor_data.py
    habitat   — Habitat/HM3D RGB-D episodes
    gnm       — GNM/ViNT trajectory datasets (h5, npz, or dirs format)

Usage:
    python scripts/convert_to_lerobot.py \
        --dataset robothor \
        --data-dir data/robothor \
        --output-dir data/lerobot/robothor_nav

    python scripts/convert_to_lerobot.py \
        --dataset habitat \
        --data-dir data/raw/habitat \
        --output-dir data/lerobot/habitat_nav

    python scripts/convert_to_lerobot.py \
        --dataset gnm \
        --format h5 \
        --data-dir data/raw/gnm \
        --output-dir data/lerobot/gnm_nav
"""

from __future__ import annotations

import argparse
import os
import pickle

import numpy as np
import yaml

from data_adapters.habitat_adapter import HabitatAdapter
from data_adapters.robothor_adapter import RoboTHORAdapter
from data_adapters.gnm_adapter import GNMAdapter
from data_adapters.data_splitter import split_trajectories
from lerobot_conversion.unified_to_lerobot import UnifiedToLeRobotConverter
from reward.reward_calculator import RewardCalculator, RewardConfig


def _save_split_data(split_data, path: str) -> None:
    """Save split data (with nested dicts) to disk."""
    obs = split_data["observations"]
    info = split_data.get("info", {})

    # Separate the nested dicts for saving
    save_dict = {}
    for k, v in split_data.items():
        if k == "observations":
            continue
        save_dict[k] = v

    for k, v in obs.items():
        save_dict[f"obs_{k}"] = v

    for k, v in info.items():
        save_dict[f"info_{k}"] = v

    np.savez_compressed(path, **save_dict)


def _load_split_data(path: str) -> dict:
    """Load split data from disk."""
    data = np.load(path, allow_pickle=True)
    loaded = dict(data)

    result = {"observations": {}, "info": {}}

    for k, v in loaded.items():
        if k.startswith("obs_"):
            result["observations"][k[4:]] = v
        elif k.startswith("info_"):
            result["info"][k[5:]] = v
        else:
            result[k] = v

    return result


def main():
    parser = argparse.ArgumentParser(
        description="Convert public dataset to LeRobot format"
    )
    parser.add_argument("--dataset", type=str, required=True,
                        choices=["robothor", "habitat", "gnm"])
    parser.add_argument("--format", type=str, default="h5",
                        help="GNM file format: h5, npz, dirs")
    parser.add_argument("--data-dir", type=str, required=True)
    parser.add_argument("--output-dir", type=str, required=True)
    parser.add_argument("--config", type=str, default="configs/new/default.yaml")
    parser.add_argument("--no-scan64-from-meta", action="store_true",
                        help="Recompute Scan64 from depth (slower)")
    args = parser.parse_args()

    # Load config
    with open(args.config) as f:
        config = yaml.safe_load(f)

    # Create adapter
    if args.dataset == "robothor":
        adapter = RoboTHORAdapter(
            data_dir=args.data_dir,
            scan_dim=64,
            image_size=(224, 224),
            load_scan64_from_meta=not args.no_scan64_from_meta,
        )
    elif args.dataset == "habitat":
        adapter = HabitatAdapter(
            data_dir=args.data_dir,
            scan_dim=64,
            image_size=(224, 224),
            depth_available=True,
        )
    elif args.dataset == "gnm":
        adapter = GNMAdapter(
            data_dir=args.data_dir,
            file_format=args.format,
            depth_available=False,
        )
    else:
        raise ValueError(f"Unknown dataset: {args.dataset}")

    # Convert to unified format
    print(f"Loading {args.dataset} dataset from {args.data_dir}...")
    unified_data = adapter.convert_all()
    T_total = len(unified_data["actions"])
    n_eps = len(np.unique(unified_data["episode_ids"]))
    print(f"Loaded {T_total} transitions across {n_eps} episodes")

    # Split into train/val/test
    train_data, val_data, test_data = split_trajectories(
        unified_data,
        train_frac=0.7,
        val_frac=0.15,
        test_frac=0.15,
    )
    print(f"Split: train={len(train_data['actions'])}, "
          f"val={len(val_data['actions'])}, "
          f"test={len(test_data['actions'])}")

    # Relabel rewards
    reward_cfg = config.get("reward", {})
    reward_weights = reward_cfg.get("weights", {})
    rc = RewardConfig(
        w_progress=reward_weights.get("progress", 1.0),
        w_obstacle=reward_weights.get("obstacle", 0.5),
        w_smoothness=reward_weights.get("smoothness", 0.1),
        w_intervention=reward_weights.get("intervention", 1.0),
        w_collision=reward_weights.get("collision", 5.0),
        w_success=reward_weights.get("success", 10.0),
    )
    calculator = RewardCalculator(rc)

    for split_name, split_data in [
        ("train", train_data),
        ("val", val_data),
        ("test", test_data),
    ]:
        print(f"Relabeling rewards for {split_name}...")
        rewards = calculator.compute_rewards(split_data)
        split_data["rewards"] = rewards
        mean_r = float(np.mean(rewards))
        print(f"  {split_name}: mean reward = {mean_r:.4f}")

    # Convert train to LeRobot format
    converter = UnifiedToLeRobotConverter(output_dir=args.output_dir)
    converter.convert(train_data)

    # Save val/test splits
    val_path = args.output_dir + "_val"
    test_path = args.output_dir + "_test"
    _save_split_data(val_data, val_path + ".npz")
    _save_split_data(test_data, test_path + ".npz")

    # Save a small metadata file with conversion info
    info = {
        "dataset": args.dataset,
        "data_dir": args.data_dir,
        "total_transitions": T_total,
        "total_episodes": n_eps,
        "train_transitions": len(train_data["actions"]),
        "val_transitions": len(val_data["actions"]),
        "test_transitions": len(test_data["actions"]),
    }
    import json
    with open(os.path.join(args.output_dir, "conversion_info.json"), "w") as f:
        json.dump(info, f, indent=2)

    print(f"\nDone!")
    print(f"  Train (LeRobot): {args.output_dir}")
    print(f"  Val:             {val_path}.npz")
    print(f"  Test:            {test_path}.npz")
    print(f"\nNext step:")
    print(f"  python scripts/train_iql.py \\")
    print(f"      --data-dir {args.output_dir} \\")
    print(f"      --output-dir checkpoints/iql_{args.dataset}")


if __name__ == "__main__":
    main()
