"""
Placeholder: Residual safety model training.

In Phase 2, this module will use the synthetic RGB-D data generated by
``sim.synthetic_rgbd`` together with rollouts from ``LeKiwiScanEnv`` to
train a lightweight residual model (e.g. a small CNN or MLP) that predicts
collision risk from (RGB, depth, scan) observations.

The residual model will be deployed on the real AGV as a safety-filter
layer that modulates the base policy's velocity commands.

Implementation will live in ``learning/`` and use PyTorch.  This file
provides an importable entry point and docstrings describing the planned
architecture.

Currently stubbed out -- train with::

    python -m sim.mujoco_lekiwi.train_residual --config configs/safety_model.yaml

Data flow:
    1. Synthetic RGB-D scenes  →  residual risk labels  (sim/synthetic_rgbd)
    2. LeKiwiScanEnv rollouts  →  (obs, action, collision) tuples
    3. Supervised training on concatenated features
    4. Export to TorchScript for real-time inference on the AGV

Architecture (planned):
    - RGB branch:  MobileNetV3-Small backbone → 64-D embedding
    - Depth branch: same backbone, shared or separate → 64-D embedding
    - Scan branch:  2-layer MLP (64→32→16)
    - Fusion:  concat → MLP (64+64+16=144 → 32 → 1)  sigmoid output
    - Loss:  binary cross-entropy (collision / no-collision)
"""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


def main():
    """Placeholder entry point for residual model training."""
    logger.info(
        "Residual safety model training is not yet implemented.\n"
        "This will be added in Phase 2 (see learning/ module).\n"
        "For now, synthetic data generation is available via:\n"
        "    python -m sim.synthetic_rgbd.render_dataset"
    )


if __name__ == "__main__":
    main()
